### ISSUE TITLE
error when during install of version 1.23.3

### ISSUE THREAD

**Issue by zaibon** [rugamoto/socket-v2-sdk#11]
When installing this library version 1.23.3, I get the following error:
```
file: /vercel/path0/node_modules/.pnpm/@socket.tech+socket-v2-sdk@1.23.3/node_modules/@socket.tech/socket-v2-sdk/lib/src/index.js
13:44:02.742 | [vite-plugin-sveltekit-compile] Failed to resolve entry for package "@socket.tech/ll-core". The package may have incorrect main/module/exports specified in its package.json.
13:44:02.742 | file: /vercel/path0/node_modules/.pnpm/@socket.tech+socket-v2-sdk@1.23.3/node_modules/@socket.tech/socket-v2-sdk/lib/src/index.js
13:44:02.747 | error during build:
13:44:02.747 | Error: Failed to resolve entry for package "@socket.tech/ll-core". The package may have incorrect main/module/exports specified in its package.json.
13:44:02.747 | at packageEntryFailure (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
13:44:02.747 | at resolvePackageEntry (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
13:44:02.747 | at tryNodeResolve (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
13:44:02.747 | at Object.resolveId (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
13:44:02.748 | at file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
13:44:02.748 | at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
13:44:02.748 | at async resolveId (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24117:26)
13:44:02.748 | at async ModuleLoader.resolveId (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24531:15)
13:44:02.748 | at async file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:8107:16
13:44:02.748 | at async Promise.all (index 1)
13:44:02.770 | ELIFECYCLE  Command failed with exit code 1.
13:44:02.790 | Error: Command "pnpm build" exited with 1
13:44:03.182
```

**Comment by rookmate** [comment]
Closing the Issue as the repository will be archived shortly.
